adminbase/adminbase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.conf.urls import url, include
from django.views.generic import TemplateView, RedirectView
from django.urls import reverse_lazy

urlpatterns = [
    url(r'^$',RedirectView.as_view(url=reverse_lazy('authorization:login'))),
    url(r'^admin/', admin.site.urls),
    #-- Login/Dashboard
    url(r'^panel/', include(('panel.login.urls','login'), namespace='authorization')),
    #-- Config
    url(r'^panel/config/', include(('panel.config.urls','config'), namespace='config')),
    #-- Usuarios
    url(r'^panel/accounts/', include(('panel.accounts.urls','accounts'), namespace='usuarios')),
    #-- Transportistas
    url(r'^panel/carriers/', include(('panel.carriers.urls','carriers'), namespace='transportista')),
    #-- Personal
    url(r'^panel/profile/', include(('panel.profile.urls','personal'), namespace='perfil')),
    #-- Personal
    url(r'^panel/routes/', include(('panel.routes.urls','routes'), namespace='rutas')),
    #-- Ubicaciones
    url(r'^panel/locations/', include(('panel.locations.urls','locations'), namespace='ubicacion')),
    #-- Clientes
    url(r'^panel/customers/', include(('panel.customers.urls','customers'), namespace='clientes')),
    #-- Mercancias
    url(r'^panel/commodities/', include(('panel.commodities.urls','commodities'), namespace='mercancias')),
    #-- Equipos
    url(r'^panel/equipments/', include(('panel.equipments.urls','equipments'), namespace='equipos')),
    #-- Posicion - Empleados
    url(r'^panel/position/', include(('panel.position.urls','position'), namespace='Posicion')),
    #-- Empleado - Empleados
    url(r'^panel/employees/', include(('panel.employees.urls','employees'), namespace='Empleados')),
    #-- Fletes
    url(r'^panel/freight/', include(('panel.freight.urls','freight'), namespace='Fletes')),
    #-- Matchs
    url(r'^panel/matchs/', include(('panel.matchs.urls','matchs'), namespace='Matchs')),
    #-- Prospects
    url(r'^panel/prospects/', include(('panel.prospects.urls','prospects'), namespace='Prospectos')),
    #-- Reortes
    url(r'^panel/reports/', include(('panel.reports.urls','reports'), namespace='Reportes')),

    #-- Recovery Password
    url(r'^recovery/', include('django.contrib.auth.urls')),
    #-- Summernote texteditor
    url(r'^summernote/', include('django_summernote.urls')),
    #-- Django Select2
    url(r'^select2/', include('django_select2.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminbase/panel/login/urls.py
from django.conf.urls import url
from panel.login.views import authorization

urlpatterns = [
	
	#-- Dashboard
	url(r'^$', authorization.dashboard, name='dashboard'),
	#-- Login
    url(r'^login/$', authorization.login_account, name='login'),
    #-- Logout
    url(r'^logout/$', authorization.logout_account, name='logout'),

    url(r'^reset/$', authorization.reset_password, name='password_reset'),
#     url(r'^reset/done/$',
#         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
#         name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        authorization.reset_password_confirm, name='password_reset_confirm')
#     url(r'^reset/complete/$',
#         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
#         name='password_reset_complete'),
]

adminbase/panel/prospects/urls.py
from django.conf.urls import url
from .views import prospects
from .views import interest

urlpatterns = [
    url(r'^$', prospects.prospect_list, name='prospect_list'),
	url(r'^add/$', prospects.prospect_add, name='prospect_add'),
	url(r'^edit/(?P<pk>[0-9]+)/$', prospects.prospect_edit, name='prospect_edit'),
	url(r'^delete/(?P<pk>[0-9]+)/$', prospects.prospect_delete, name='prospect_delete'),
	url(r'^confirm/(?P<prospect_id>[0-9]+)/$', interest.interest_confirm, name='interest_confirm'),

	url(r'^interest/(?P<pk>[0-9]+)/$', interest.interest_list, name='interest_list'),
	# url(r'^interest/add/(?P<pk>[0-9]+)/$', interest.interest_add, name='interest_add'),
	url(r'^interest/edit/(?P<pk>[0-9]+)/$', interest.interest_edit, name='interest_edit'),
	url(r'^interest/documents/(?P<prospect_id>[0-9]+)/$', interest.interest_documents, name='interest_documents'),
	url(r'^interest/sendmail/(?P<prospect_id>[0-9]+)/$', interest.interest_sendmail, name='interest_sendmail'),
	url(r'^interest/approve/(?P<pk>[0-9]+)/$', interest.interest_approve, name='interest_approve'),
	url(r'^interest/approve/ask/(?P<prospect_id>[0-9]+)/$', interest.interest_approve_form, name='interest_approve_form'),

	url(r'^routes/delete/(?P<pk>[0-9]+)/$', interest.interest_route_delete, name='interest_route_delete'),
	url(r'^equipments/delete/(?P<pk>[0-9]+)/$', interest.interest_equipment_delete, name='interest_equipment_delete'),

]

adminbase/panel/prospects/models.py
import os

from django.db import models
from django_extensions.db.models import TimeStampedModel

from panel.core.utils import get_filename
from panel.core.validators import validate_file_extension, validate_pdf_extension

from panel.equipments.models import Equipment
from cities.models import City, Region

from django.urls import reverse

MEDIA_CHOICES = [
    ('', 'Seleccione un medio'),
    ('recommended', 'Recomendado'),
    ('pension', 'Pension'),
    ('web page', 'Pagina web'),
    ('facebook', 'Facebook')
]
PROSPECT_STATUS_CHOICES = [
    ('pd', 'Prospeccion'),
    ('pr', 'Interesado'),
    ('wa', 'En espera'),
    ('ap', 'Aprovado'),
    ('na', 'No apto')
]

def get_file(intance, filename):
	name, ext = os.path.splitext(filename)

	return 'prospect/documents/%s' % get_filename(ext)

def get_image(instance, filename):
    name, ext = os.path.splitext(filename)

    return 'prospect/images/%s' % get_filename(ext)

# Create your models here.
class Prospect(TimeStampedModel):
    medio = models.CharField(max_length=20,choices=MEDIA_CHOICES,verbose_name='Media')
    name = models.CharField(verbose_name='Nombre', max_length=300)
    source = models.ForeignKey(City, related_name='source_path_prospect', verbose_name='Ruta origen de interes', on_delete=models.DO_NOTHING, null=True)
    target = models.ForeignKey(City, related_name='target_path_prospect', verbose_name='Ruta destino de interes', on_delete=models.DO_NOTHING, null=True)
    phone = models.CharField(verbose_name='Telefono', max_length=20)
    picture = models.ImageField(upload_to=get_image,validators=[validate_file_extension],verbose_name='Imagen', null=True, blank=True)
    prospect_status = models.CharField(max_length=20, choices=PROSPECT_STATUS_CHOICES, default='pd', verbose_name='Status del prospecto')
    
    status = models.BooleanField(verbose_name='status', default=True)

    class Meta:
        db_table = 'prospect'
        verbose_name = 'Prospecto'
        verbose_name_plural = 'Prospectos'
        
    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class Interest(TimeStampedModel):
    prospect = models.ForeignKey(Prospect, related_name='prospect_interest', verbose_name='Prospecto interesado', on_delete=models.CASCADE)
    phone = models.CharField(verbose_name='Telefono de oficina', max_length=20, null=True)
    email = models.EmailField(max_length=120, verbose_name='Email')
    person_type = models.CharField(verbose_name='Tipo de persona', max_length=10)

    # Document
    tax_number = models.FileField(upload_to=get_file, verbose_name='RFC', null=True)
    oficial_id = models.FileField(upload_to=get_file, verbose_name='Identificacion', null=True)
    transport_allowance = models.FileField(upload_to=get_file, verbose_name='Permiso de transporte', null=True)
    proof_address = models.FileField(upload_to=get_file, verbose_name='Comprobante de domicilio', null=True)
    e_billin_demo = models.FileField(upload_to=get_file, verbose_name='Factura electronica demo', null=True)
    bank_statement = models.FileField(upload_to=get_file, verbose_name='Estado de cuenta', null=True)
    unity_list = models.FileField(upload_to=get_file, verbose_name='Relacion de unidades', null=True)
    contract = models.FileField(upload_to=get_file, verbose_name='Contrato', null=True)
    constitutive_act = models.FileField(upload_to=get_file, verbose_name='Acta constitutiva', null=True)
    power_attorney = models.FileField(upload_to=get_file, verbose_name='Poder de los representante', null=True)
    payment_authorization = models.FileField(upload_to=get_file, verbose_name='Autorizacion para pagos', null=True)
    
    # 
    driving_license = models.FileField(upload_to=get_file, verbose_name='Licencia', null=True)
    insurance = models.FileField(upload_to=get_file, verbose_name='Seguro de la unidad', null=True)
    registration = models.FileField(upload_to=get_file, verbose_name='Tarjeta de circulacion', null=True)
    gps = models.FileField(upload_to=get_file, verbose_name='GPS', null=True)
    mirror_account = models.FileField(upload_to=get_file, verbose_name='Cuenta espejo', null=True)
    # --

    equipments = models.ManyToManyField(Equipment, through='InterestEquipment')
    
    status = models.BooleanField(verbose_name='status', default=True)

    class Meta:
        db_table = 'prospect_interested'
        verbose_name = 'Prospecto'
        verbose_name_plural = 'Prospectos'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

class InterestEquipment(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE)
    quantity = models.SmallIntegerField(verbose_name="cantidad", default=1)
    
    def get_absolute_url(self):
        return reverse('prospects:interest_equipment_delete', kwargs={'pk': self.pk})


class InterestRoutes(models.Model):
    interest = models.ForeignKey(Interest, related_name='prospect_routes', on_delete=models.CASCADE)
    source_path = models.ForeignKey(City, related_name="prospect_source", verbose_name="Ruta origen", max_length=100, on_delete=models.DO_NOTHING)
    source_path_region = models.ForeignKey(Region, related_name="prospect_source_region", verbose_name="Estado origen", max_length=100, on_delete=models.DO_NOTHING)
    target_path = models.ForeignKey(City, related_name="prospect_target", verbose_name="Ruta destino", max_length=100, on_delete=models.DO_NOTHING, null=True)
    target_path_region = models.ForeignKey(Region, related_name="prospect_target_region", verbose_name="Estado destino", max_length=100, on_delete=models.DO_NOTHING, null=True)

    def get_absolute_url(self):
        return reverse('prospects:interest_route_delete', kwargs={'pk': self.pk})

adminbase/panel/prospects/views/prospects.py
from django.shortcuts import render
from ..models import Prospect, Interest
from ..forms import ProspectForm
from ..views import interest

from django.contrib import messages
from panel.core.utils import user_logs, delete_record, delete_item
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist

from panel.core.decorators import has_permissions
from django.contrib.auth.decorators import login_required

# Create your views here.

app_name = __package__.rsplit('.')[1]
@login_required
@has_permissions('can_view_' + app_name)
def prospect_list(request):
	context = {}

	context['permissions'] = request.user.get_user_permissions(request.user)
	context['app_name'] = app_name
	context['filter'] = request.GET.get('filter')
	context['prospect_list'] = Prospect.objects.filter(status=True).order_by('name')

	return render(request, 'prospects/prospect_list.html', context)

@login_required
@has_permissions('can_add_' + app_name)
def prospect_add(request):
	context = {}

	if request.method == 'POST':
		context['prospect_form'] = ProspectForm(request.POST,request.FILES)

		if context['prospect_form'].is_valid():
			prospect_obj = context['prospect_form'].save(commit=False)
			prospect_obj.save()

			#-- Message to beneficiary
			msg = messages.success(request, 'Prospecto creado satisfactorimente')

			#-- User Logs (Info, Access, Error)
			user_logs(request,None,'I','Prospecto creado satisfactorimente')

			return redirect('prospects:prospect_list')
	else:
		context['prospect_form'] = ProspectForm()
	
	return render(request, 'prospects/prospect_form.html', context)
	
@login_required
@has_permissions('can_edit_' + app_name)
def prospect_edit(request, pk):
	context = {}

	context['prospect_obj'] = get_object_or_404(Prospect, pk=pk)
	
	try:
		obj = Interest.objects.get(prospect_id = context['prospect_obj'].pk)
		return redirect('prospects:interest_edit', str(obj.pk))
	except MultipleObjectsReturned:
		pass
	except ObjectDoesNotExist:
		pass

	if request.method == 'POST':
		context['prospect_form'] = ProspectForm(request.POST,request.FILES, instance=context['prospect_obj'])

		if context['prospect_form'].is_valid():
			prospect_obj = context['prospect_form'].save(commit=False)	
			prospect_obj.save()

			msg = messages.success(request, 'Prospecto modificado satisfactorimente')

			#-- User Logs (Info, Access, Error)
			user_logs(request,None,'I','Prospecto modificado satisfactorimente')

			return redirect('prospects:prospect_list')
	else:
		context['prospect_form'] = ProspectForm(instance=context['prospect_obj'])

	return render(request, 'prospects/prospect_form.html', context)

# def prospect_interest(request, pk):
# 	prospect = get_object_or_404(Prospect, pk=pk)
# 	data = interest.interest_confirm(request, prospect.pk, 'prospects:prospect_interest')
# 	return JsonResponse(data, safe=False)

def prospect_call(request, pk):
	pass

@login_required
@has_permissions('can_delete_' + app_name)
def prospect_delete(request, pk):
	prospect = get_object_or_404(Prospect, pk=pk)

	data = delete_record(request, prospect, '/panel/prospects/', 'prospects:prospect_delete')
	return JsonResponse(data)

adminbase/panel/prospects/templates/prospects/documents_carousel.html
{% load user_agents %}

<div class="modal-header">
    <h2>Documentos</h2>
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
</div>

<div class="modal-body">
    <div class="row">

        {% if documents_list %}
        <div class="{% if documents_missing %} col-sm-6 {% else %} col-sm-12 {% endif %}">
            <h6 class="m-0 font-weight-bold text-primary">
                Documentos subidos
            </h6>
            <ul class="list-group">
                {% for document in documents_list %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-sm-8">
                                {{document.title}}
                            </div>
                            <div class="col-sm-4 text-right">
                                <span class="btn btn-sm btn-primary btn-file fileinput-new">                                        
                                    <a href="{{document.file.url}}" target="_blank" style="text-decoration:none; color:white;"><i class="fa fa-eye"></i> Ver</a>
                                </span>
                            </div>
                        </div>
                    </li>
                    
                
                {% endfor %}
            </ul>
            <br> 
        </div>
        {% endif %}
        {% if documents_missing %}
        <div class="{% if documents_list %} col-sm-6 {% else %} col-sm-12 {% endif %}">
            <h6 class="m-0 font-weight-bold text-primary">
                Documentos faltantes
            </h6>
            <ul class="list-group">
                {% for document in documents_missing %}
                    <li class="list-group-item">{{document}}</li>
                {% endfor %}
            </ul>
            <br> 
        </div>
        {% endif %}

        <div class="col-sm-12">
            
            {% if documents_list and not request|is_mobile %}
            <div id="demo" class="carousel slide" data-ride="carousel">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                  {% for count in documents_list %}
                  <li data-target="#demo" data-slide-to="{{forloop0.counter" class="{% if forloop.counter == 1%}active{% endif %}"></li>
                  {% endfor %}
                </ul>
              
                <!-- The slideshow -->
                <div class="carousel-inner">
                  {% for document in documents_list %}
                  

                  <div class="carousel-item {% if forloop.counter == 1%}active{% endif %}">
                    {% if document.is_pdf %}
                    <iframe src="https://googledriveembedder.collegefam.com/?key=YOUR_API_KEY&folderid=FOLDER_ID_WHIHCH_IS_PUBLICLY_VIEWABLE" class="responsive"></iframe>
                    {% else %}
                    <img src="{{document.file.url}}" alt="{{document.title}}" class="responsive">
                    {% endif %}
                    <div class="carousel-caption">
                        <h3 class="text-gray-800">{{document.title}}</h3>
                        <!-- <p class="text-gray-500"></p> -->
                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <div class="btn-group">
                                <span class="btn btn-sm btn-primary btn-file fileinput-new">                                        
                                    <a href="{{document.file.url}}" target="_blank" style="text-decoration:none; color:white;"><i class="fa fa-eye"></i> Ver</a>
                                </span>
                            </div>
                        </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              
                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                  <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                  <span class="carousel-control-next-icon"></span>
                </a>
              
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cerrar</button>
</div>

adminbase/panel/prospects/templates/prospects/interest_approve_form.html
<form method="POST" action="" class="create-form" autocomplete="off">{% csrf_token %}
    <div class="modal-header">
        <h2>Confirmar</h2>
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
    </div>
    <div class="modal-body">
        <div class="row">
            {% if prospect_form.errors %}
            <div class="alert alert-warning">
                <button class="close" data-close="alert"></button><i class="icon fa fa-warning"></i> Tiene algunos errores. Favor de verificarlos 
            </div>
            {% endif %}
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            {{interest_confirm_form.email}}
        </div>
    </div>
    <div class="col-sm-12 div_person_type">
        <div class="text-center">
            <div class="form-group{% if interest_confirm_form.person_type.errors %} has-error{% endif %}">
                {% for radio in interest_confirm_form.person_type %}
                <label class="btn btn-primary" for="{{ radio.id_for_label }}">
                    {{ radio.choice_label }}
                    <span class="radio">{{ radio.tag }}</span>
                </label>
                {% endfor %}  
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-sm btn-success">Confirmar</button>
        <button type="button" class="btn btn-sm btn-white" data-dismiss="modal">Cancelar</button> 
    </div>
</form>

<script>
    $("#id_email").val('hide@hotmail.com');
    $("#id_person_type_0").attr('checked', true);
    // $(".div_person_type").hide();
    // $("#id_email").hide();

</script>

adminbase/panel/prospects/templates/prospects/prospect_list.html
{% extends 'base.html' %}

{% block subtitle %}Prospectos{% endblock subtitle %}

{% block header %}Lista de prospectos{% endblock header %}

{% block headerbutton %}
    <div>
        {% with perm='can_add_'|add:app_name %}   
            {% if perm in permissions or user.is_superuser %}
            <a href="{% url 'prospects:prospect_add' %}" class="btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-plus text-white-50"></i> Agregar prospecto
            </a>
            {% endif %}
        {% endwith %}
        <a href="{% url 'authorization:dashboard' %}" class="btn btn-sm btn-secondary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-left"></i>
            </span>
            <span class="text">Regresar</span>
        </a>
    </div>
{% endblock headerbutton %}

         
{% block subheader %}{% endblock subheader %}

{% block customcss %}
  
{% endblock customcss %}

{% block content %}

{% load user_agents %}
{% load thumbnail %}

<div class="col-xl-12">
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="form-group">
                <input type="text" id="myFilter" class="form-control" onkeyup="myFunction()" placeholder="Buscar prospecto...">
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="form-group">
                <input type="text" id="filterStatus" class="form-control" onkeyup="filterStatus()" placeholder="Buscar x status...">
            </div>
        </div>
    </div>
    <div class="row" id="prospects">
        {% for prospect in prospect_list %}
        <div class="col-xl-3 col-md-6 mb-4 cards-col">
            <div class="card shadow table_list">
                <div class="card-header d-flex flex-row justify-content-between {% if prospect.prospect_status == 'pd' %} bg-warning {% elif prospect.prospect_status == 'pr' %} bg-primary {% elif prospect.prospect_status == 'wa' %} bg-success {% else %} bg-danger {% endif %}">
                    <div class="h6 text-white"><strong>{{prospect.get_prospect_status_display}}</strong></div>
                    <div>
                        {% with perm='can_edit_'|add:app_name %}   
                            {% if perm in permissions or user.is_superuser %}
                            <a href="{% url 'prospects:prospect_edit' prospect.pk %}" class="btn btn-sm btn-warning btn-circle" style="border-color: white;">
                                <i class="fas fa-edit"></i>
                            </a>
                            {% endif %}
                        {% endwith %}
                        {% with perm='can_delete_'|add:app_name %}   
                            {% if perm in permissions or user.is_superuser %}
                            <button data-url="{% url 'prospects:prospect_delete' prospect.pk %}" title="Eliminar" class="btn btn-sm btn-danger btn-circle js-view-delete" style="border-color: white;">
                                <i class="fa fa-trash"></i>
                            </button>
                            {% endif %}
                        {% endwith %}
                    </div>
                </div>
                <div class="card-body">
                    
                    <div class="row no-gutters align-items-center text-center">
                        <div class="col-sm-12 px-5 pb-1">
                            {% if prospect.picture %}
                                {% thumbnail prospect.picture '100x100' crop='center' as img %}
                                <img src="{{img.url}}" class="rounded-circle img-responsive2">{% endthumbnail %}
                            {% else %}
                                <img class="rounded-circle img-responsive2" src="{{STATIC_URL}}img/user.png">
                            {% endif %}
                            </div>
                        <div class="col-sm-12">
                            <div class="h6 mb-0 font-weight-bold text-gray-800">{{prospect.name}}</div>
                        </div>
                        <div class="col-sm-12 mb-2">
                            <small>
                                <i class="fa fa-phone-alt"></i>{{prospect.phone}}
                            </small>
                        </div>
                        <div class="col-sm-12">
                            <div class="small">
                            {% if prospect.prospect_interest.count > 0 %}
                                {% for interest in prospect.prospect_interest.all %}
                                    {% for route in interest.prospect_routes.all %}
                                        {{route.source_path}} <i class="fas fa-long-arrow-alt-right"></i> {{route.target_path}}
                                        <br>
                                    {% endfor %}
                                {% endfor %}
                            {% else %}
                                {{prospect.source}} <i class="fas fa-long-arrow-alt-right"></i> {{prospect.target}}
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    {% if prospect.prospect_status == 'pd' %}
                        <button data-url="{% url 'prospects:interest_confirm' prospect.pk %}" title="Interesado" class="btn btn-primary btn-circle js-create">
                            <i class="fas fa-star"></i>
                        </button>
                    {% else %}
                        {% if prospect.prospect_status == 'wa' %}
                            <button data-url="{% url 'prospects:interest_approve_form' prospect.pk %}" title="Documentos" class="btn btn-success btn-circle js-create">
                                <i class="fas fa-check"></i>
                            </button>
                        {% endif %}
                        <button data-url="{% url 'prospects:interest_documents' prospect.pk %}" title="Documentos" class="btn btn-info btn-circle js-create">
                            <i class="fas fa-file"></i>
                        </button>
                        {% if request|is_mobile %}
                            <a class="btn btn-primary btn-circle" href="tel:{{prospect.phone}}"><i class="fa fa-phone"></i></a>
                        {% else %}
                            <button data-url="{% url 'prospects:interest_sendmail' prospect.pk %}" title="Correo" class="btn btn-warning btn-circle js-create">
                                <i class="fas fa-envelope"></i>
                            </button>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="modal inmodal fade" id="modal_form" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        </div>
    </div>
</div>
  

<script>
    function myFunction() {
        var input, filter, cards, cardContainer, h5, title, i;
        input = document.getElementById("myFilter");
        filter = input.value.toUpperCase();
        cardContainer = document.getElementById("prospects");
        cards = cardContainer.getElementsByClassName("cards-col");
        for (i = 0; i < cards.length; i++) {
            title = cards[i].querySelector(".card-body div.h6");
            if (title.innerText.toUpperCase().indexOf(filter) > -1) {
                cards[i].style.display = "";
            } else {
                cards[i].style.display = "none";
            }
        }
    }

    function filterStatus() {
        var input, filter, cards, cardContainer, h5, title, i;
        input = document.getElementById("filterStatus");
        filter = input.value.toUpperCase();
        cardContainer = document.getElementById("prospects");
        cards = cardContainer.getElementsByClassName("cards-col");
        for (i = 0; i < cards.length; i++) {
            title = cards[i].querySelector(".card-header div.h6");
            if (title.innerText.toUpperCase().indexOf(filter) > -1) {
                cards[i].style.display = "";
            } else {
                cards[i].style.display = "none";
            }
        }
    }
</script>
{% endblock content %}


{% block docready %}
    {% if filter %}
        $("#myFilter").val('{{filter}}');
        myFunction();
    {% endif %}

{% endblock docready %}