adminbase/adminbase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.conf.urls import url, include
from django.views.generic import TemplateView, RedirectView
from django.urls import reverse_lazy

urlpatterns = [
    url(r'^$',RedirectView.as_view(url=reverse_lazy('authorization:login'))),
    url(r'^admin/', admin.site.urls),
    #-- Login/Dashboard
    url(r'^panel/', include(('panel.login.urls','login'), namespace='authorization')),
    #-- Config
    url(r'^panel/config/', include(('panel.config.urls','config'), namespace='config')),
    #-- Usuarios
    url(r'^panel/accounts/', include(('panel.accounts.urls','accounts'), namespace='usuarios')),
    #-- Transportistas
    url(r'^panel/carriers/', include(('panel.carriers.urls','carriers'), namespace='transportista')),
    #-- Personal
    url(r'^panel/profile/', include(('panel.profile.urls','personal'), namespace='perfil')),
    #-- Personal
    url(r'^panel/routes/', include(('panel.routes.urls','routes'), namespace='rutas')),
    #-- Ubicaciones
    url(r'^panel/locations/', include(('panel.locations.urls','locations'), namespace='ubicacion')),
    #-- Clientes
    url(r'^panel/customers/', include(('panel.customers.urls','customers'), namespace='clientes')),
    #-- Mercancias
    url(r'^panel/commodities/', include(('panel.commodities.urls','commodities'), namespace='mercancias')),
    #-- Equipos
    url(r'^panel/equipments/', include(('panel.equipments.urls','equipments'), namespace='equipos')),
    #-- Posicion - Empleados
    url(r'^panel/position/', include(('panel.position.urls','position'), namespace='Posicion')),
    #-- Empleado - Empleados
    url(r'^panel/employees/', include(('panel.employees.urls','employees'), namespace='Empleados')),
    #-- Fletes
    url(r'^panel/freight/', include(('panel.freight.urls','freight'), namespace='Fletes')),
    #-- Matchs
    url(r'^panel/matchs/', include(('panel.matchs.urls','matchs'), namespace='Matchs')),
    #-- Prospects
    url(r'^panel/prospects/', include(('panel.prospects.urls','prospects'), namespace='Prospectos')),
    #-- Reortes
    url(r'^panel/reports/', include(('panel.reports.urls','reports'), namespace='Reportes')),

    #-- Recovery Password
    url(r'^recovery/', include('django.contrib.auth.urls')),
    #-- Summernote texteditor
    url(r'^summernote/', include('django_summernote.urls')),
    #-- Django Select2
    url(r'^select2/', include('django_select2.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminbase/panel/login/urls.py
from django.conf.urls import url
from panel.login.views import authorization

urlpatterns = [
	
	#-- Dashboard
	url(r'^$', authorization.dashboard, name='dashboard'),
	#-- Login
    url(r'^login/$', authorization.login_account, name='login'),
    #-- Logout
    url(r'^logout/$', authorization.logout_account, name='logout'),

    url(r'^reset/$', authorization.reset_password, name='password_reset'),
#     url(r'^reset/done/$',
#         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
#         name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        authorization.reset_password_confirm, name='password_reset_confirm')
#     url(r'^reset/complete/$',
#         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
#         name='password_reset_complete'),
]

adminbase/panel/login/models.py
from django.db import models

# Create your models here.

adminbase/panel/login/forms.py
from django import forms
from panel.config.models import MenuItems

class LoginForm(forms.Form):
	email = forms.EmailField(
		label = 'Email',
		error_messages = {'required' : 'Email incorrecto'},
		widget = forms.EmailInput(
			attrs = {
				'class' : 'form-control form-control-user',
				'aria-describedby' : "emailHelp",
				'placeholder' : 'Ingrese su email...',
			}
		)
	)
	password = forms.CharField(
		label = 'Contraseña',
		error_messages = {'required' : 'Contraseña incorrecta'},
		widget = forms.PasswordInput(
			attrs = {
				'class' : 'form-control form-control-user',
				'placeholder' : 'Contraseña'
			}
		)
	)

class ResetPasswordForm(forms.Form):
	email = forms.EmailField(
		error_messages = {'required' : 'Email incorrecto'},
		widget = forms.EmailInput(
			attrs = {
				'class' : 'form-control form-control-user',
				'aria-describedby' : "emailHelp",
				'placeholder' : 'Ingrese su email...',
			}
		)
	)


class MenuSearchForm(forms.Form):
	menu = forms.ModelChoiceField(
		label='Buscar',
		required = False,
		queryset = MenuItems.objects.all(),
		empty_label = 'Buscar...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)
	

adminbase/panel/login/views/authorization.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.core.cache import cache 
from panel.core.authentication_email import EmailAuthBackend
from panel.core.utils import user_logs
from panel.core.context_processors import menu_user
from panel.accounts.models import User
from panel.login.forms import LoginForm, ResetPasswordForm, MenuSearchForm
from panel.routes.models import Route
from django.contrib import messages

from django.db.models import Count


# Create your views here.
def login_account(request):
	context = {}

	if request.user.is_authenticated:
		return redirect('authorization:dashboard')
	else:
		if request.method == 'POST':
			context['form_login'] = LoginForm(request.POST)

			if context['form_login'].is_valid():
				user = EmailAuthBackend.authenticate(None,email=context['form_login'].cleaned_data['email'], \
									password=context['form_login'].cleaned_data['password'])
				if user is not None:
					if user.is_active and user.status:
						login(request, user)

						#-- Delete Redis cache
						cache.delete('menu_%s' % (request.user.pk))
						cache.delete('menu_%s' % (request.user.pk))
						cache.delete('datapanel')

						msg = messages.success(request, 'Bienvenido a Logistica Naves')

						#-- User Logs (Info, Access, Error)
						user_logs(request,None,'A','Acceso al sistema')

						if request.GET.get('next'):
							return redirect(request.GET.get('next'))
						else:
							return redirect('authorization:dashboard')
					else:
						context['message'] = 'Usuario o contraseña incorrectos'

						#-- User Logs (Info, Access, Error)
						user_logs(request,user,'E','Usuario o contraseña incorrectos')
				else:
					context['message'] = 'Usuario o contraseña incorrectos'
			else:
				context['message'] = 'Datos incorrectos'
				
		else:
			context['form_login'] = LoginForm()
	return render(request, 'login/login.html', context)

def dashboard(request):
	context = menu_user(request)
	context['menu_form'] = MenuSearchForm()

	source = Route.objects.all().values('source__region__code', 'source__region__name').annotate(quantity=Count('*')).order_by('quantity')
	target = Route.objects.all().values('target__region__code', 'target__region__name').annotate(quantity=Count('*')).order_by('quantity')
	
	data_source = []
	total_quantity = 0
	for s in source:
		total_quantity += s['quantity']

	for s in source:
		percentage = s['quantity'] / total_quantity * 100
		dicc = {
			'name': s['source__region__name'],
			'code': s['source__region__code'], 
			'quantity': s['quantity'],
			'percentage': round(percentage, 2)
			}
		if percentage <= 1: dicc['category'] = 1
		elif percentage <= 5: dicc['category'] = 2
		elif percentage <= 10: dicc['category'] = 3
		elif percentage <= 15: dicc['category'] = 4
		elif percentage <= 20: dicc['category'] = 5
		elif percentage <= 30: dicc['category'] = 6
		elif percentage <= 50: dicc['category'] = 7
		data_source.append(dicc)
		
	data_target = []
	total_quantity = 0
	for t in target:
		total_quantity += t['quantity']

	for t in target:
		percentage = t['quantity'] / total_quantity * 100
		dicc = {
			'name': t['target__region__name'],
			'code': t['target__region__code'], 
			'quantity': t['quantity'],
			'percentage': round(percentage, 2)
			}
		if percentage <= 1: dicc['category'] = 1
		elif percentage <= 5: dicc['category'] = 2
		elif percentage <= 10: dicc['category'] = 3
		elif percentage <= 15: dicc['category'] = 4
		elif percentage <= 20: dicc['category'] = 5
		elif percentage <= 30: dicc['category'] = 6
		elif percentage <= 50: dicc['category'] = 7
		data_target.append(dicc)
	
	context['data_source'] = data_source
	context['data_target'] = data_target

	# if request.user_agent.is_mobile:
	# 	context['is_mobile'] = True
	# else:
	# 	context['is_mobile'] = False
	return render(request, 'login/dashboard.html', context)

def logout_account(request):

	#-- User Logs (Info, Access, Error)
	user_logs(request,None,'A','Cierre de Sesión')

	logout(request)

	return redirect('authorization:login')

def reset_password(request):
	context = {}
	context['reset_password_form'] = ResetPasswordForm(request.POST or None)


	return render(request, 'login/password_reset.html', context)

def reset_password_confirm(request):
	pass

adminbase/panel/login/templates/login/login.html
{% extends 'base_login.html' %}

{% block subtitle %}Login{% endblock subtitle %}

{% block content %}

<div class="col-xl-10 col-lg-12 col-md-9">
  
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-6 d-none d-lg-block">
            <img src="{{datapanel.logo.url}}" height="100%" width="100%">
          </div>
          
          <div class="col-lg-6">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Bienvenidos!</h1>
              </div>
              <form class="user" action="" method="POST">
                {% csrf_token %}
                {% if message %}
                <div class="alert alert-warning">
                  <i class="icon fab fa-warning"></i> {{message}}
                </div>
                {% endif %}
                <div class="form-group">
                  {{form_login.email}}
                </div>
                <div class="form-group">
                  {{form_login.password}}
                </div>
                <div class="form-group">
                  <div class="custom-control custom-checkbox small">
                    <input type="checkbox" class="custom-control-input" id="customCheck">
                    <label class="custom-control-label" for="customCheck">Recordarme</label>
                  </div>
                </div>
                <button type="submit" class="btn btn-primary btn-user btn-block">Iniciar Sesión</button>
                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Login with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                </a>
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="{% url 'authorization:password_reset' %}">Olvidaste tu Contraseña?</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>

{% endblock content %}

adminbase/panel/login/templates/login/password_reset.html
{% extends 'base_login.html' %}

{% block subtitle %}Restablecer contraseña{% endblock subtitle %}

{% block content %}

<div class="col-xl-10 col-lg-12 col-md-9">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-2">¿Olvidaste tu contraseña?</h1>
                            <p class="mb-4">
                                Lo entendemos, suele pasar. Solo ingresa tu email debajo y 
                                te enviaremos un link para restablecer tu contraseña!
                            </p>
                        </div>
                        <form role="form" method="post" action="" enctype="multipart/form-data" novalidate>
                            {% csrf_token %}
                            {% include 'core/snippets/form_messages.html' with form=carrier_form %}
                            <div class="form-group">
                                {{reset_password_form.email}}
                            </div>
                            <button type="submit" class="btn btn-primary btn-user btn-block">Restablecer Contraseña</button>

                        </form>
                        <hr>

                        <div class="text-center">
                            <a class="small" href="{% url 'authorization:login' %}">¿Ya tienes una cuenta? Ingresa aqui!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock content %}

adminbase/panel/login/templates/login/password_reset_confirm.html
{% extends 'base_login.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Contraseña cambiada!</h3>
          <div class="alert alert-success" role="alert">
            Se ha cambiado tu contraseña de manera exitosa! ya puedes ir al inicio de sesion.
          </div>
          <a href="{% url 'authorization:login' %}" class="btn btn-secondary btn-block">Inicio de sesion</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

adminbase/panel/login/templates/login/password_reset_done.html
{% extends 'base_login.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reinicie su contraseña</h3>
          <p>Verifique un enlace en su email para establecer su contraseña. Si no aparece espere unos minutos, cheque su carpeta de spam.</p>
          <a href="{% url 'authorization:login' %}" class="btn btn-secondary btn-block">Regrese al inicio de sesion</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

adminbase/panel/login/templates/login/password_reset_email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta name="viewport" content="width=device-width" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>{{websitename}}</title>
        <style>
            /* -------------------------------------
                GLOBAL
                A very basic CSS reset
            ------------------------------------- */
            * {
                margin: 0;
                padding: 0;
                font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
                box-sizing: border-box;
                font-size: 14px;
            }

            img {
                max-width: 100%;
            }

            body {
                -webkit-font-smoothing: antialiased;
                -webkit-text-size-adjust: none;
                width: 100% !important;
                height: 100%;
                line-height: 1.6;
            }

            /* Let's make sure all tables have defaults */
            table td {
                vertical-align: top;
            }

            /* -------------------------------------
                BODY & CONTAINER
            ------------------------------------- */
            body {
                background-color: #f6f6f6;
            }

            .body-wrap {
                background-color: #f6f6f6;
                width: 100%;
            }

            .container {
                display: block !important;
                max-width: 600px !important;
                margin: 0 auto !important;
                /* makes it centered */
                clear: both !important;
            }

            .content {
                max-width: 600px;
                margin: 0 auto;
                display: block;
                padding: 20px;
            }

            /* -------------------------------------
                HEADER, FOOTER, MAIN
            ------------------------------------- */
            .main {
                background: #fff;
                border: 1px solid #e9e9e9;
                border-radius: 3px;
            }

            .content-wrap {
                padding: 20px;
            }

            .content-block {
                padding: 0 0 20px;
            }

            .header {
                width: 100%;
                margin-bottom: 20px;
            }

            .footer {
                width: 100%;
                clear: both;
                color: #999;
                padding: 20px;
            }
            .footer a {
                color: #999;
            }
            .footer p, .footer a, .footer unsubscribe, .footer td {
                font-size: 12px;
            }

            /* -------------------------------------
                TYPOGRAPHY
            ------------------------------------- */
            h1, h2, h3 {
                font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
                color: #000;
                margin: 40px 0 0;
                line-height: 1.2;
                font-weight: 400;
            }

            h1 {
                font-size: 32px;
                font-weight: 500;
            }

            h2 {
                font-size: 24px;
            }

            h3 {
                font-size: 18px;
            }

            h4 {
                font-size: 14px;
                font-weight: 600;
            }

            p, ul, ol {
                margin-bottom: 10px;
                font-weight: normal;
            }
            p li, ul li, ol li {
                margin-left: 5px;
                list-style-position: inside;
            }

            /* -------------------------------------
                LINKS & BUTTONS
            ------------------------------------- */
            a {
                color: #1ab394;
                text-decoration: underline;
            }

            .btn-primary {
                text-decoration: none;
                color: #FFF;
                background-color: #1ab394;
                border: solid #1ab394;
                border-width: 5px 10px;
                line-height: 2;
                font-weight: bold;
                text-align: center;
                cursor: pointer;
                display: inline-block;
                border-radius: 5px;
                text-transform: capitalize;
            }

            /* -------------------------------------
                OTHER STYLES THAT MIGHT BE USEFUL
            ------------------------------------- */
            .last {
                margin-bottom: 0;
            }

            .first {
                margin-top: 0;
            }

            .aligncenter {
                text-align: center;
            }

            .alignright {
                text-align: right;
            }

            .alignleft {
                text-align: left;
            }

            .clear {
                clear: both;
            }

            /* -------------------------------------
                ALERTS
                Change the class depending on warning email, good email or bad email
            ------------------------------------- */
            .alert {
                font-size: 16px;
                color: #fff;
                font-weight: 500;
                padding: 20px;
                text-align: center;
                border-radius: 3px 3px 0 0;
            }
            .alert a {
                color: #fff;
                text-decoration: none;
                font-weight: 500;
                font-size: 16px;
            }
            .alert.alert-warning {
                background: #f8ac59;
            }
            .alert.alert-bad {
                background: #ed5565;
            }
            .alert.alert-good {
                background: #1ab394;
            }

            /* -------------------------------------
                INVOICE
                Styles for the billing table
            ------------------------------------- */
            .invoice {
                margin: 40px auto;
                text-align: left;
                width: 80%;
            }
            .invoice td {
                padding: 5px 0;
            }
            .invoice .invoice-items {
                width: 100%;
            }
            .invoice .invoice-items td {
                border-top: #eee 1px solid;
            }
            .invoice .invoice-items .total td {
                border-top: 2px solid #333;
                border-bottom: 2px solid #333;
                font-weight: 700;
            }

            /* -------------------------------------
                RESPONSIVE AND MOBILE FRIENDLY STYLES
            ------------------------------------- */
            @media only screen and (max-width: 640px) {
                h1, h2, h3, h4 {
                    font-weight: 600 !important;
                    margin: 20px 0 5px !important;
                }

                h1 {
                    font-size: 22px !important;
                }

                h2 {
                    font-size: 18px !important;
                }

                h3 {
                    font-size: 16px !important;
                }

                .container {
                    width: 100% !important;
                }

                .content, .content-wrap {
                    padding: 10px !important;
                }

                .invoice {
                    width: 100% !important;
                }
            }    
        </style>
    </head>

    <body>

        <table class="body-wrap">
            <tr>
                <td></td>
                <td class="container" width="600">
                    <div class="content">
                        <table class="main" width="100%" cellpadding="0" cellspacing="0">
                            <tr>
                                <td class="alert alert-good">
                                    <b>{{websitename}}</b>
                                </td>
                            </tr>
                            <tr>
                                <td class="content-wrap">
                                    <table width="100%" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td class="content-block">
                                                Usted está recibiendo este correo porque se esta intentando restablecer su contraseña para el usuario: {{ user.username }}.
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="content-block">
                                                Si usted esta recibiendo este correo por error, es muy probable que otro usuario alla ingresado su usuario 
                                                por error cuando trataba de recuperar su contraseña. Si tu no solicitaste esta recuperacion de contraseña, 
                                                no necesitas realizar ninguna accion futura y puedes ignorar con seguridad este correo.

                                                Gracias,

                                                Logistica Naves Admin.
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="content-block">
                                                <a href="{{ domain }}{% url 'login:password_reset_confirm' uidb64=uid token=token %}" class="btn-primary">Recuperar contraseña</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="content-block">
                                                O copie y pegue el enlace en la barra de dirección de su navegador:<br>
                                                <a href="{{ domain }}{% url 'login:password_reset_confirm' uidb64=uid token=token %}">{{ domain }}{% url 'accounts:accounts_activation' uidb64=uid token=token %}</a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                        <div class="footer">
                            <table width="100%">
                                <tr>
                                    <td class="aligncenter content-block"><a href="{{website}}">Copyright © {{websitename}}</a></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </td>
                <td></td>
            </tr>
        </table>

    </body>
</html>

adminbase/panel/login/templates/login/password_reset_subjet.html
[3plnaves] Por favor restablesca su contraseña