adminbase/adminbase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.conf.urls import url, include
from django.views.generic import TemplateView, RedirectView
from django.urls import reverse_lazy

urlpatterns = [
    url(r'^$',RedirectView.as_view(url=reverse_lazy('authorization:login'))),
    url(r'^admin/', admin.site.urls),
    #-- Login/Dashboard
    url(r'^panel/', include(('panel.login.urls','login'), namespace='authorization')),
    #-- Config
    url(r'^panel/config/', include(('panel.config.urls','config'), namespace='config')),
    #-- Usuarios
    url(r'^panel/accounts/', include(('panel.accounts.urls','accounts'), namespace='usuarios')),
    #-- Transportistas
    url(r'^panel/carriers/', include(('panel.carriers.urls','carriers'), namespace='transportista')),
    #-- Personal
    url(r'^panel/profile/', include(('panel.profile.urls','personal'), namespace='perfil')),
    #-- Personal
    url(r'^panel/routes/', include(('panel.routes.urls','routes'), namespace='rutas')),
    #-- Ubicaciones
    url(r'^panel/locations/', include(('panel.locations.urls','locations'), namespace='ubicacion')),
    #-- Clientes
    url(r'^panel/customers/', include(('panel.customers.urls','customers'), namespace='clientes')),
    #-- Mercancias
    url(r'^panel/commodities/', include(('panel.commodities.urls','commodities'), namespace='mercancias')),
    #-- Equipos
    url(r'^panel/equipments/', include(('panel.equipments.urls','equipments'), namespace='equipos')),
    #-- Posicion - Empleados
    url(r'^panel/position/', include(('panel.position.urls','position'), namespace='Posicion')),
    #-- Empleado - Empleados
    url(r'^panel/employees/', include(('panel.employees.urls','employees'), namespace='Empleados')),
    #-- Fletes
    url(r'^panel/freight/', include(('panel.freight.urls','freight'), namespace='Fletes')),
    #-- Matchs
    url(r'^panel/matchs/', include(('panel.matchs.urls','matchs'), namespace='Matchs')),
    #-- Prospects
    url(r'^panel/prospects/', include(('panel.prospects.urls','prospects'), namespace='Prospectos')),
    #-- Reortes
    url(r'^panel/reports/', include(('panel.reports.urls','reports'), namespace='Reportes')),

    #-- Recovery Password
    url(r'^recovery/', include('django.contrib.auth.urls')),
    #-- Summernote texteditor
    url(r'^summernote/', include('django_summernote.urls')),
    #-- Django Select2
    url(r'^select2/', include('django_select2.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminbase/panel/login/urls.py
from django.conf.urls import url
from panel.login.views import authorization

urlpatterns = [
	
	#-- Dashboard
	url(r'^$', authorization.dashboard, name='dashboard'),
	#-- Login
    url(r'^login/$', authorization.login_account, name='login'),
    #-- Logout
    url(r'^logout/$', authorization.logout_account, name='logout'),

    url(r'^reset/$', authorization.reset_password, name='password_reset'),
#     url(r'^reset/done/$',
#         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
#         name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        authorization.reset_password_confirm, name='password_reset_confirm')
#     url(r'^reset/complete/$',
#         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
#         name='password_reset_complete'),
]

adminbase/panel/routes/urls.py
from django.conf.urls import url
from panel.routes.views import routes

urlpatterns = [
    url(r'^$', routes.routes_list, name='routes_list'),
    url(r'^add/$', routes.routes_add, name='routes_add'),
    url(r'^note/(?P<pk>[0-9]+)/(?P<source_id>[0-9]+)/(?P<target_id>[0-9]+)/$', routes.routes_note, name='routes_note'),
    url(r'^note/(?P<pk>[0-9]+)/$', routes.routes_note, name='routes_note'),
    url(r'^note/add/(?P<pk>[0-9]+)/(?P<source_id>[0-9]+)/(?P<target_id>[0-9]+)/$', routes.routes_note, name='routes_note'),

]

adminbase/panel/routes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os


from django.db import models
from django_extensions.db.models import TimeStampedModel

from cities.models import City, Region
from panel.accounts.models import User
from panel.customers.models import Customer
from panel.carriers.models import Carriers
from panel.notifications.models import Notification


NOTE_OPTIONS = [
    ('no equipment', 'No tiene equipo'),
    ('paid problem', 'Problemas de pago'),
    ('disponibility check', 'Revisa disponibilidad'),
    ('no route', 'No maneja esa ruta'),
    ('put equipment', 'Coloca equipo'),
    ('other', 'Otros')
]

# Create your models here.

class Route(models.Model):
    date = models.DateField(null=True)
    consignment_note = models.CharField(verbose_name="Carta porte", max_length=10, unique=True, null=True)
    customer = models.ForeignKey(Customer, related_name = 'customer_route', verbose_name = 'Cliente', null=True, on_delete=models.CASCADE)
    carrier = models.ForeignKey(Carriers, related_name = 'carrier_route', verbose_name = 'Transportista', on_delete=models.CASCADE)
    source = models.ForeignKey(City, related_name = 'source_route', verbose_name = 'Origen', on_delete=models.CASCADE)
    target = models.ForeignKey(City, related_name = 'target_route', verbose_name = 'Destino', on_delete=models.CASCADE)
    

    class Meta:
        db_table = 'route'
        verbose_name = 'Ruta'
        verbose_name_plural = 'Rutas'

    def __str__(self):
        return self.carrier.alias + ' - ' + self.source.name + ' a ' + self.target.name

class LastFilterRoute(TimeStampedModel):
    source_region = models.ForeignKey(Region, related_name="last_source_region", verbose_name="Estado origen", max_length=100, default='', null=True, on_delete=models.DO_NOTHING)
    source_path = models.ForeignKey(City, related_name="last_source_path", verbose_name="Ruta origen", max_length=100, on_delete=models.DO_NOTHING)
    target_region = models.ForeignKey(Region, related_name="last_target_region", verbose_name="Estado destino", max_length=100, default='', null=True, on_delete=models.DO_NOTHING)
    target_path = models.ForeignKey(City, related_name="last_target_path", verbose_name="Ruta destino", max_length=100, on_delete=models.DO_NOTHING, null=True)
    source_radio = models.PositiveSmallIntegerField(verbose_name='Radio origen',default=0)
    target_radio = models.PositiveSmallIntegerField(verbose_name='Radio destino',default=0)
    
    user = models.ForeignKey(User, related_name = 'route_filter_user', verbose_name = 'Filtro de rutas de usuario', on_delete=models.CASCADE)

    class Meta:
        db_table = 'filter_route'
        verbose_name = 'Filtro'
        verbose_name_plural = 'Filtros'

    def __unicode__(self):
        return self.source_pat.name + ' a ' + self.target_path.name   
    
    def __str__(self):
        return self.source_path.name + ' a ' + (self.target_path.name if self.target_path else 'nada')

class Note(TimeStampedModel):
    user = models.ForeignKey(User, related_name='user_notes', verbose_name="Notas de usuario", on_delete=models.CASCADE)
    carrier = models.ForeignKey(Carriers, related_name='notes', verbose_name='Transportista', on_delete=models.CASCADE)
    source = models.ForeignKey(City, related_name="source_note", verbose_name="Ruta origen", max_length=100, on_delete=models.DO_NOTHING, null=True)
    target = models.ForeignKey(City, related_name="target_note", verbose_name="Ruta destino", max_length=100, on_delete=models.DO_NOTHING, null=True)
    note = models.CharField(verbose_name='Nota', max_length=1000, null=True)
    options = models.CharField(max_length=100, choices=NOTE_OPTIONS, default='', verbose_name='Opciones')
    mail = models.ForeignKey(Notification, related_name='mail_notes', verbose_name='Mensaje', null=True, on_delete=models.DO_NOTHING)
    
    is_reported = models.BooleanField(verbose_name="status", null=True)


    class Meta:
        db_table = 'route_notes'
        verbose_name = 'Note'
        verbose_name_plural = 'Notes'

adminbase/panel/routes/forms.py
# -*- coding: utf-8 -*-
from django import forms

from panel.routes.models import Route, LastFilterRoute, Note, NOTE_OPTIONS
from panel.carriers.models import Carriers
from panel.customers.models import Customer
from cities.models import City, Region

CHOICES=[('carrier','Transportistas'),
		 ('customer','Clientes')]


SEARCH_TYPE = (
	('0', 'Ambos'),
	('1', 'Buscar solo por origen')
	# ('2', 'Buscar solo por destino')
)

class RouteForm(forms.ModelForm):
	date = forms.DateField(
		label = 'Fecha',
		error_messages = {'required' : 'Debe capturar la fecha de la ruta'},
		widget = forms.DateInput(
			attrs = {
				'class' : 'form-control',
			}
		)
	)

	customer = forms.ModelChoiceField(
		label='Cliente',
		required = False, # Temporal
		# error_messages = {'required' : 'Debe capturar el cliente'}, Todavia no se desarrolla el modulo de clientes
		queryset = Customer.objects.filter(status=True),
		empty_label = 'Seleccione al cliente...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	carrier = forms.ModelChoiceField(
		label='Transportista',
		error_messages = {'required' : 'Debe capturar el transportista'},
		queryset = Carriers.objects.filter(status=True),
		empty_label = 'Seleccione al transportista...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	source = forms.ModelChoiceField(
		label='Ciudad origen',
		error_messages = {'required' : 'Debe capturar la ruta origen'},
		queryset = City.objects.filter(country_id=3996063),
		empty_label = 'Seleccione el origen...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	target = forms.ModelChoiceField(
		label='Ciudad destino',
		error_messages = {'required' : 'Debe capturar la ruta destino'},
		queryset = City.objects.filter(country_id=3996063),
		empty_label = 'Seleccione el destino...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	source_region = forms.ModelChoiceField(
		label='Estado origen',
		error_messages = {'required' : 'Debe capturar el estado'},
		queryset = Region.objects.filter(country_id=3996063).order_by('name'),
		empty_label = 'Seleccione el estado...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	target_region = forms.ModelChoiceField(
		label='Estado destino',
		error_messages = {'required' : 'Debe capturar el estado'},
		queryset = Region.objects.filter(country_id=3996063).order_by('name'),
		empty_label = 'Seleccione el estado...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	class Meta:
		model = Route
		fields = ('date', 'customer', 'carrier', 'source', 'target')


class RouteFilterForm(forms.ModelForm):
	source_path = forms.ModelChoiceField(
		label='Ciudad origen',
		error_messages = {'required' : 'Debe capturar la ruta origen'},
		queryset = City.objects.filter(country_id=3996063),
		empty_label = 'Seleccione el origen...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)
	source_region = forms.ModelChoiceField(
		label='Estado origen',
		required = False,
		queryset = Region.objects.filter(country_id=3996063).order_by('name'),
		empty_label = 'Seleccione el estado...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	target_path = forms.ModelChoiceField(
		label='Ciudad destino',
		required=False,
		queryset = City.objects.filter(country_id=3996063),
		empty_label = 'Seleccione el destino...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)
	target_region = forms.ModelChoiceField(
		label='Estado destino',
		required = False,
		queryset = Region.objects.filter(country_id=3996063).order_by('name'),
		empty_label = 'Seleccione el estado...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)
	source_radio = forms.CharField(
		label = 'Radio origen',
		required = False,
		initial = 0,
		widget = forms.TextInput(
			attrs = {
				'class': 'touchspin',
			}
		)
	 )
	target_radio = forms.CharField(
		label = 'Radio destino',
		required = False,
		initial = 0,
		widget = forms.TextInput(
			attrs = {
				'class': 'touchspin',
			}
		)
	 )

	person_type = forms.ChoiceField(
		choices=CHOICES, 
		widget=forms.RadioSelect(
			attrs = {
				'class': 'color simple_tag'
			}
		)
	)

	search_type = forms.ChoiceField(
		choices=SEARCH_TYPE, 
		widget=forms.RadioSelect(
			attrs = {
				'class': 'color simple_tag'
			}
		)
	)

	class Meta:
		 model = LastFilterRoute
		 fields = ('source_region', 'source_path', 'target_region', 'target_path', 'source_radio', 'target_radio',)

class NoteForm(forms.ModelForm):
	options = forms.ChoiceField(
		label = "Observaciones",
		required = False,
		choices = NOTE_OPTIONS,
		widget = forms.Select(attrs={"class": "form-control",}),
	)
	note = forms.CharField(
		label="Comentarios",
		required = False,
		widget=forms.Textarea(attrs={"rows": 4, "class": "form-control",}),
	)

	class Meta:
		model = Note
		fields = ('note', 'options')

adminbase/panel/routes/admin.py
from django.contrib import admin

# Register your models here.

adminbase/panel/routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'routes'

adminbase/panel/routes/tests.py
from django.test import TestCase

# Create your tests here.

adminbase/panel/routes/templates/routes/routes_filter.html
{% extends 'base.html' %}
{% load user_agents %}
{% load humanize %}

{% block subtitle %}Rutas{% endblock subtitle %}

{% block header %}Informacion de rutas{% endblock header %}

{% block headerbutton %}
  <div>
    {% with perm='can_add_'|add:app_name %}   
        {% if perm in permissions or user.is_superuser %}
        <a href="{% url 'routes:routes_add' %}" class="btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus text-white-50"></i> Agregar ruta</a>
        {% endif %}
    {% endwith %}
    <a href="{% url 'authorization:dashboard' %}" class="btn btn-sm btn-secondary btn-icon-split">
      <span class="icon text-white-50">
        <i class="fas fa-arrow-left"></i>
      </span>
      <span class="text">Regresar</span>
    </a>
  </div>
{% endblock headerbutton %}
         
{% block subheader %}{% endblock subheader %}

{% block customcss %}
  <link href="{{STATIC_URL}}plugins/touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{STATIC_URL}}plugins/jquery_ui/jquery-ui.css">  
{% endblock %}



{% block content %}

<!-- Filtros recientes -->
<div class="col-xl-3 col-md-4">
  <div class="card shadow mb-4">
      <div class="card-header d-sm-flex align-items-center justify-content-between py-3">
          <h6 class="m-0 font-weight-bold text-primary">Filtros recientes</h6>
      </div>
      <div class="card-body small">
          
          {% for filter in last_filters%}
          <div class="row">
              <div class="col-sm-12">
                <div class="font-weight-bold">
                  <div class="text-truncate">
                    <a class="last_search" href="#" data-source="{{filter.source_path.pk}}" data-target="{{filter.target_path.pk}}">                        
                      <span class="source">{{filter.source_path}}</span>
                      <span><i class="fas fa-long-arrow-alt-right"></i></span>
                      <span class="target">{{filter.target_path}}</span>
                    </a>
                  </div>
                  <div class="text-gray-500">{{filter.last|naturaltime}}</div>
                </div>
              </div>
          </div>
          {% endfor %}
      </div>
  </div>
  <div class="modal inmodal fade" id="modal_form" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        </div>
    </div>
  </div>
</div>

<div class="col-xl-9 col-md-8 filter">
  <form method="POST" action="" class="create-form" autocomplete="off">
    {% csrf_token %}
    {% include 'core/snippets/form_messages.html' with form=mail_form %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Filtro</h6>
          <button type="submit" class="btn btn-sm btn-light btn-icon-split" type="button">
            <span class="icon text-gray-600">
              <i class="fas fa-search"></i>
            </span>
            <span class="text">Buscar</span>
          </button>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="row">
            {% for radio in route_form.person_type %}
            <div class="col-sm-4">
                {{ radio }}
            </div>
            {% endfor %}
          </div>
          <div id="div_source" class="row">
            <div class="form-group col-sm-4">
              <label for="{{route_form.source_region.label}}">{{route_form.source_region.label}}</label>
              {{route_form.source_region}}
              {% for error in route_form.source_region.errors %}
                  <span class='help-block has-error help-block-error'>{{error}}</span>
              {% endfor %}
            </div>
            <div class="form-group col-sm-4">
              <label for="{{route_form.source_path.label}}">{{route_form.source_path.label}}</label>
              {{route_form.source_path}}
              {% for error in route_form.source_path.errors %}
                  <span class='help-block has-error help-block-error'>{{error}}</span>
              {% endfor %}
            </div>
            <div class="form-group col-sm-3">
              <label for="{{route_form.source_radio.label}}">{{route_form.source_radio.label}}</label>
              {{route_form.source_radio}}
              {% for error in route_form.source_radio.errors %}
                  <span class='help-block has-error help-block-error'>{{error}}</span>
              {% endfor %}
            </div>
          </div>

          <div id="div_target" class="row">
            <div class="form-group col-sm-4">
              <label for="{{route_form.target_region.label}}">{{route_form.target_region.label}}</label>
                {{route_form.target_region}}
                {% for error in route_form.target_region.errors %}
                    <span class='help-block has-error help-block-error'>{{error}}</span>
                {% endfor %}
            </div>
            <div class="form-group col-sm-4">
              <label for="{{route_form.target_path.label}}">{{route_form.target_path.label}}</label>
              {{route_form.target_path}}
              {% for error in route_form.target_path.errors %}
                  <span class='help-block has-error help-block-error'>{{error}}</span>
              {% endfor %}
            </div>
            <div class="form-group col-sm-3">
              <label for="{{route_form.target_radio.label}}">{{route_form.target_radio.label}}</label>
              {{route_form.target_radio}}
              {% for error in route_form.target_radio.errors %}
                  <span class='help-block has-error help-block-error'>{{error}}</span>
              {% endfor %}
            </div>
          </div>
          
          <div class="row">
            {% for radio in route_form.search_type %}
            <div class="col-sm-4">
                {{ radio }}
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
  </form>
</div>

{% endblock content %}


{% block customjs %}
  <script src="{{STATIC_URL}}plugins/touchspin/jquery.bootstrap-touchspin.min.js"></script>
  <script src="{{STATIC_URL}}plugins/jquery_ui/jquery-ui.js"></script>
  <script src="{{STATIC_URL}}js/routes.js?1"></script>
{% endblock %}

{% block docready %}
    $( function() {
      $( document ).tooltip();
    } );

    $(".dataTable").DataTable({
      "order": [[ 0, "desc" ]]
    });
    $(".select2").select2({width: '100%'});
    $(".touchspin").TouchSpin({
      min: 0,
      max: 2500,
      step: 10,
      boostat: 5,
      maxboostedstep: 10,
      buttondown_class: 'btn btn-light',
      buttonup_class: 'btn btn-light'
     });

    $("#id_person_type_0").prop("checked", true);
    $("#id_search_type_0").prop("checked", true);

    $(".last_search").on('click', function(){
      var ahref = $(this);
      var source = ahref.attr("data-source");
      var target = ahref.attr("data-target");

      $("#id_source_path").select2('val', source)
      $("#id_target_path").select2('val', target);
    });

{% endblock docready %}

adminbase/panel/routes/templates/routes/routes_form.html
{% extends 'base.html' %}

{% block subtitle %}routes{% endblock subtitle %}

{% block header %} {% if route_obj %} Editar {% else %} Crear {% endif %} route {% endblock header %}

{% block headerbutton %}
  <a href="{% url 'routes:routes_list' %}" class="btn btn-sm btn-secondary btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-arrow-left"></i>
    </span>
    <span class="text">Regresar</span>
  </a>
{% endblock headerbutton %}

{% block subheader %}{% endblock subheader %}

{% block customcss %}
<link href="{{STATIC_URL}}plugins/datepicker/datepicker3.css" rel="stylesheet">
  <style>
    #id_date_day {
        width: 19%;
    }
    #id_date_year {
        width: 30%;
    }
    #id_date_month {
        width: 50%;
    }
  </style>
{% endblock customcss %}


{% block content %}
<div class="col-xl-12">
    <form role="form" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'core/snippets/form_messages.html' with form=route_form %}
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Rutas</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="{{route_form.date.label}}">{{route_form.date.label}}</label>
                            <br>
                            {{route_form.date}}
                            {% for error in route_form.date.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-sm-5">
                        <div class="form-group">
                            <label for="{{route_form.carrier.label}}">{{route_form.carrier.label}}</label>
                            {{route_form.carrier}}
                            {% for error in route_form.carrier.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>  
                    </div>

                    <div class="col-sm-5">
                        <div class="form-group">
                            <label for="{{route_form.customer.label}}">{{route_form.customer.label}}</label>
                            {{route_form.customer}}
                            {% for error in route_form.customer.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>  
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{route_form.source_region.label}}">{{route_form.source_region.label}}</label>
                            {{route_form.source_region}}
                            {% for error in route_form.source_region.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{route_form.source.label}}">{{route_form.source.label}}</label>
                            {{route_form.source}}
                            {% for error in route_form.source.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{route_form.target_region.label}}">{{route_form.target_region.label}}</label>
                            {{route_form.target_region}}
                            {% for error in route_form.target_region.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>  
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                        <label for="{{route_form.target.label}}">{{route_form.target.label}}</label>
                        {{route_form.target}}
                        {% for error in route_form.target.errors %}
                            <span class='help-block has-error help-block-error'>{{error}}</span>
                        {% endfor %}
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group text-right">
                            <button class="btn btn-sm btn-success" type="submit">Guardar</button>
                            <a href="{% url 'routes:routes_list' %}" class="btn btn-sm btn-white">Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content%}

{% block customjs %}
    <script src="{{STATIC_URL}}plugins/datepicker/bootstrap-datepicker.js"></script>
{% endblock customjs %}

{% block docready %}
    {% include 'core/snippets/form_validation.html' with form=route_form %}
    {% include 'core/snippets/messages_error.html' with form=route_form %}

   $(".select2").select2();

   $('#id_date').datepicker({
    'format': 'yyyy-mm-dd',
    'isRTL': 'false',
    'autoclose':'true',
    'language': 'es',
   });
{% endblock docready %}

adminbase/panel/routes/templates/routes/routes_notes.html
<form method="POST" action="" class="create-form" autocomplete="off">{% csrf_token %}

    <div class="modal-header">
        <h2>Observaciones</h2>
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
    </div>

    <div class="modal-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="{{note_form.options.label}}">{{note_form.options.label}}</label>
                    {{note_form.options}}
                    {% for error in note_form.options.errors %}
                        <span class='help-block has-error help-block-error'>{{error}}</span>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label for="{{note_form.note.label}}">{{note_form.note.label}}</label>
                    {{note_form.note}}
                    {% for error in note_form.note.errors %}
                        <span class='help-block has-error help-block-error'>{{error}}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Guardar</button>
        <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cerrar</button>
    </div>

</form>