adminbase/adminbase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.conf.urls import url, include
from django.views.generic import TemplateView, RedirectView
from django.urls import reverse_lazy

urlpatterns = [
    url(r'^$',RedirectView.as_view(url=reverse_lazy('authorization:login'))),
    url(r'^admin/', admin.site.urls),
    #-- Login/Dashboard
    url(r'^panel/', include(('panel.login.urls','login'), namespace='authorization')),
    #-- Config
    url(r'^panel/config/', include(('panel.config.urls','config'), namespace='config')),
    #-- Usuarios
    url(r'^panel/accounts/', include(('panel.accounts.urls','accounts'), namespace='usuarios')),
    #-- Transportistas
    url(r'^panel/carriers/', include(('panel.carriers.urls','carriers'), namespace='transportista')),
    #-- Personal
    url(r'^panel/profile/', include(('panel.profile.urls','personal'), namespace='perfil')),
    #-- Personal
    url(r'^panel/routes/', include(('panel.routes.urls','routes'), namespace='rutas')),
    #-- Ubicaciones
    url(r'^panel/locations/', include(('panel.locations.urls','locations'), namespace='ubicacion')),
    #-- Clientes
    url(r'^panel/customers/', include(('panel.customers.urls','customers'), namespace='clientes')),
    #-- Mercancias
    url(r'^panel/commodities/', include(('panel.commodities.urls','commodities'), namespace='mercancias')),
    #-- Equipos
    url(r'^panel/equipments/', include(('panel.equipments.urls','equipments'), namespace='equipos')),
    #-- Posicion - Empleados
    url(r'^panel/position/', include(('panel.position.urls','position'), namespace='Posicion')),
    #-- Empleado - Empleados
    url(r'^panel/employees/', include(('panel.employees.urls','employees'), namespace='Empleados')),
    #-- Fletes
    url(r'^panel/freight/', include(('panel.freight.urls','freight'), namespace='Fletes')),
    #-- Matchs
    url(r'^panel/matchs/', include(('panel.matchs.urls','matchs'), namespace='Matchs')),
    #-- Prospects
    url(r'^panel/prospects/', include(('panel.prospects.urls','prospects'), namespace='Prospectos')),
    #-- Reortes
    url(r'^panel/reports/', include(('panel.reports.urls','reports'), namespace='Reportes')),

    #-- Recovery Password
    url(r'^recovery/', include('django.contrib.auth.urls')),
    #-- Summernote texteditor
    url(r'^summernote/', include('django_summernote.urls')),
    #-- Django Select2
    url(r'^select2/', include('django_select2.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminbase/panel/freight/urls.py
from django.conf.urls import url
from .views import freights

urlpatterns = [
    url(r'^$', freights.freight_list, name='freight_list'),
	url(r'^add/$', freights.freight_add, name='freight_add'),
	url(r'^edit/(?P<pk>[0-9]+)/$', freights.freight_edit, name='freight_edit'),
	url(r'^detail/(?P<pk>[0-9]+)/$', freights.freight_detail, name='freight_detail'),
	url(r'^delete/(?P<pk>[0-9]+)/$', freights.freight_delete, name='freight_delete'),
]

adminbase/panel/login/urls.py
from django.conf.urls import url
from panel.login.views import authorization

urlpatterns = [
	
	#-- Dashboard
	url(r'^$', authorization.dashboard, name='dashboard'),
	#-- Login
    url(r'^login/$', authorization.login_account, name='login'),
    #-- Logout
    url(r'^logout/$', authorization.logout_account, name='logout'),

    url(r'^reset/$', authorization.reset_password, name='password_reset'),
#     url(r'^reset/done/$',
#         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
#         name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        authorization.reset_password_confirm, name='password_reset_confirm')
#     url(r'^reset/complete/$',
#         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
#         name='password_reset_complete'),
]

adminbase/panel/freight/models.py
from __future__ import unicode_literals

from panel.equipments.models import Equipment
from panel.commodities.models import Commodity
from panel.employees.models import Employee
from panel.accounts.models import User
from panel.carriers.models import Carriers
from panel.customers.models import Customer

from cities.models import City

from django.db import models
from django_extensions.db.models import TimeStampedModel
# Create your models here.

class Freight(TimeStampedModel):
    title = models.CharField(verbose_name='Título', max_length=500)
    note = models.CharField(verbose_name='Título', max_length=1000)
    commodity = models.ForeignKey(Commodity, related_name="commodity_freight", verbose_name="Mercancia", on_delete=models.DO_NOTHING)
    commodity_amount = models.CharField(verbose_name='Razón Social', max_length=200)
    equipment = models.ForeignKey(Equipment, related_name="equipment_freight", verbose_name="Equipo", on_delete=models.DO_NOTHING)
    carrier = models.ForeignKey(Carriers, related_name="carrier_freight", verbose_name="Transportista", on_delete=models.DO_NOTHING)
    customer = models.ForeignKey(Customer, related_name="customer_freight", verbose_name="Cliente", on_delete=models.DO_NOTHING)
    source_path = models.ForeignKey(City, related_name="source_path_freight", verbose_name="Ruta origen", max_length=100, on_delete=models.DO_NOTHING)
    target_path = models.ForeignKey(City, related_name="target_path_freight", verbose_name="Ruta destino", max_length=100, on_delete=models.DO_NOTHING)
    cost = models.DecimalField(max_digits=8, decimal_places=2)
    user = models.ForeignKey(User, related_name = 'user_freight', verbose_name = 'Usuario transportista', null=True, on_delete=models.DO_NOTHING)

    status = models.BooleanField(verbose_name="status", default=True)

    class Meta:
        db_table = 'freights'
        verbose_name = 'Flete'
        verbose_name_plural = 'Fletes'

    def __str__(self):
        return self.title

adminbase/panel/freight/forms.py
from django import forms

from .models import Freight
from panel.commodities.models import Commodity
from panel.equipments.models import Equipment
from panel.carriers.models import Carriers
from panel.customers.models import Customer

from cities.models import City, Region

class FreightForm(forms.ModelForm):
	title = forms.CharField(
		label = 'Título',
		error_messages = {'required': 'Debe capturar un título'},
		widget = forms.TextInput(
			attrs = {
				'class' : 'form-control',
			}
		)
	)
	note = forms.CharField(
		label='Observaciones',
        max_length=1000,
		required = False,
		widget = forms.Textarea(
			attrs = {
				'class' : 'form-control',
                'rows' : 4,
			}
        )
	)
	commodity = forms.ModelChoiceField(
		label='Mercancia',
		error_messages = {'required' : 'Debe capturar la mercancia'},
		queryset = Commodity.objects.filter(status=True),
		empty_label = 'Seleccione la mercancia...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)
	
	commodity_amount = forms.DecimalField(
		label = 'Cantidad de mercancia',
 		error_messages = {'required' : 'Debe capturar la cantidad de mercancia'},
 		widget = forms.TextInput(
			attrs = {
				'class':'form-control touchspin',
			}
		)
	)

	equipment = forms.ModelChoiceField(
		label='Equipamiento',
		error_messages = {'required' : 'Debe capturar el equipamiento'},
		queryset = Equipment.objects.filter(status=True),
		empty_label = 'Seleccione el equipo...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)
	carrier = forms.ModelChoiceField(
		label='Transportista',
		error_messages = {'required' : 'Debe capturar el transportista'},
		queryset = Carriers.objects.filter(status=True),
		empty_label = 'Seleccione al transportista...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)
	customer = forms.ModelChoiceField(
		label='Cliente',
		error_messages = {'required' : 'Debe capturar el cliente'},
		queryset = Customer.objects.filter(status=True),
		empty_label = 'Seleccione al cliente...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	source_path = forms.ModelChoiceField(
		label='Ciudad origen',
		error_messages = {'required' : 'Debe capturar la ruta origen'},
		queryset = City.objects.filter(country_id=3996063),
		empty_label = 'Seleccione el origen...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	target_path = forms.ModelChoiceField(
		label='Ciudad destino',
		error_messages = {'required' : 'Debe capturar la ruta destino'},
		queryset = City.objects.filter(country_id=3996063),
		empty_label = 'Seleccione el destino...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	cost = forms.DecimalField(
		label = 'Costo',
 		required = False,
 		widget = forms.TextInput(
			attrs = {
				'class':'form-control touchspin',
			}
		)
	)

	source_region = forms.ModelChoiceField(
		label='Estado origen',
		error_messages = {'required' : 'Debe capturar el estado'},
		queryset = Region.objects.filter(country_id=3996063).order_by('name'),
		empty_label = 'Seleccione el estado...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	target_region = forms.ModelChoiceField(
		label='Estado destino',
		error_messages = {'required' : 'Debe capturar el estado'},
		queryset = Region.objects.filter(country_id=3996063).order_by('name'),
		empty_label = 'Seleccione el estado...',
		widget = forms.Select(
			attrs = {
				'class': 'form-control select2',
			}
		)
	)

	class Meta:
		model = Freight
		fields = ('title', 'note', 'commodity', 'commodity_amount', 'equipment', 'carrier', \
			'customer', 'source_path', 'target_path', 'cost')

adminbase/panel/freight/views/freights.py
from ..models import Freight
from ..forms import FreightForm

from django.db.models import Sum, Count
from django.db.models.functions import TruncMonth, TruncYear

from django.contrib import messages
from panel.core.utils import user_logs, delete_record, delete_item
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse

import datetime

from panel.core.decorators import has_permissions

# Create your views here.

app_name = __package__.rsplit('.')[1]
@has_permissions('can_view_' + app_name)
def freight_list(request):
	context = {}

	today = datetime.date.today()
	data = {}
	if (Freight.objects.filter(user=request.user)):
		if Freight.objects.filter(user=request.user, created__month=today.month):
			data = {
				'earnings_month': Freight.objects.filter(user=request.user, created__month=today.month).values('user').annotate(month=TruncMonth('created')).values('month').annotate(earnings=Sum('cost'))[0],
				'count_month': Freight.objects.filter(user=request.user, created__month=today.month).values('user').annotate(month=TruncMonth('created')).values('month').annotate(earnings=Count('*'))[0],
				'earnings_year': Freight.objects.filter(user=request.user).values('user').annotate(year=TruncYear('created')).values('year').annotate(earnings=Sum('cost'))[0],
				'count_year': Freight.objects.filter(user=request.user).values('user').annotate(year=TruncYear('created')).values('year').annotate(earnings=Count('*'))[0],
			}
		else:
			data = {
				'earnings_year': Freight.objects.filter(user=request.user).values('user').annotate(year=TruncYear('created')).values('year').annotate(earnings=Sum('cost'))[0],
				'count_year': Freight.objects.filter(user=request.user).values('user').annotate(year=TruncYear('created')).values('year').annotate(earnings=Count('*'))[0],
			}

	context['permissions'] = request.user.get_user_permissions(request.user)
	context['app_name'] = app_name
	context['freight_list'] = Freight.objects.filter(user=request.user, status=True).order_by('pk')
	context['freight_info'] = data

	return render(request, 'freights/freight_list.html', context)

@has_permissions('can_add_' + app_name)
def freight_add(request):
	context = {}

	if request.method == 'POST':
		context['freight_form'] = FreightForm(request.POST)

		if context['freight_form'].is_valid():
			freight_obj = context['freight_form'].save(commit=False)
			freight_obj.user = request.user
			freight_obj.save()

			#-- Message to beneficiary
			msg = messages.success(request, 'Flete creado satisfactorimente')

			#-- User Logs (Info, Access, Error)
			user_logs(request,None,'I','Flete creado satisfactorimente')

			return redirect('freight:freight_list')
	else:
		context['freight_form'] = FreightForm()
	
	return render(request, 'freights/freight_form.html', context)
	
@has_permissions('can_edit_' + app_name)
def freight_edit(request, pk):
	context = {}

	context['freight_obj'] = get_object_or_404(Freight, pk=pk)

	if request.method == 'POST':
		context['freight_form'] = FreightForm(request.POST,request.FILES, instance=context['freight_obj'])

		if context['freight_form'].is_valid():
			freight_obj = context['freight_form'].save(commit=False)	
			freight_obj.save()

			msg = messages.success(request, 'Flete modificado satisfactorimente')

			#-- User Logs (Info, Access, Error)
			user_logs(request,None,'I','Flete modificado satisfactorimente')

			return redirect('freight:freight_list')
	else:
		context['freight_form'] = FreightForm(instance=context['freight_obj'], \
			initial={
				'source_region': context['freight_obj'].source_path.region_id, 
				'target_region': context['freight_obj'].target_path.region_id})

	return render(request, 'freights/freight_form.html', context)

def freight_detail(request, pk):
	context = {}
	context['freight_obj'] = get_object_or_404(Freight, pk=pk)
	
	data = dict()
	data['html_form'] = render_to_string('freights/freight_detail.html', context, request=request)
	
	return JsonResponse(data)

@has_permissions('can_delete_' + app_name)
def freight_delete(request, pk):
	freight = get_object_or_404(Freight, pk=pk)

	data = delete_record(request, freight, '/panel/freight/', 'freight:freight_delete')
	return JsonResponse(data)

adminbase/panel/freight/templates/freights/freight_form.html
{% extends 'base.html' %}

{% block subtitle %}Fletes{% endblock subtitle %}

{% block header %} {% if freight_obj %} Editar {% else %} Agregar {% endif %} Flete {% endblock header %}

{% block headerbutton %}
  <a href="{% url 'freight:freight_list' %}" class="btn btn-sm btn-secondary btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-arrow-left"></i>
    </span>
    <span class="text">Regresar</span>
  </a>
{% endblock headerbutton %}

{% block subheader %}{% endblock subheader %}

{% block customcss %}
    <link href="{{STATIC_URL}}plugins/touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet">
{% endblock customcss %}



{% block content %}
<div class="col-xl-12">
    <form role="form" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'core/snippets/form_messages.html' with form=freight_form %}
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Fletes</h6>
            </div>
            <div class="card-body">
            
                <div class="row">
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="{{freight_form.title.label}}">{{freight_form.title.label}}</label>
                            {{freight_form.title}}
                            {% for error in freight_form.title.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="{{freight_form.cost.label}}">{{freight_form.cost.label}}</label>
                            {{freight_form.cost}}
                            {% for error in freight_form.cost.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>  
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{freight_form.carrier.label}}">{{freight_form.carrier.label}}</label>
                            {{freight_form.carrier}}
                            {% for error in freight_form.carrier.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>  
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{freight_form.customer.label}}">{{freight_form.customer.label}}</label>
                            {{freight_form.customer}}
                            {% for error in freight_form.customer.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>  
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{freight_form.source_region.label}}">{{freight_form.source_region.label}}</label>
                            {{freight_form.source_region}}
                            {% for error in freight_form.source_region.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{freight_form.source_path.label}}">{{freight_form.source_path.label}}</label>
                            {{freight_form.source_path}}
                            {% for error in freight_form.source_path.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                        <label for="{{freight_form.target_region.label}}">{{freight_form.target_region.label}}</label>
                        {{freight_form.target_region}}
                        {% for error in freight_form.target_region.errors %}
                            <span class='help-block has-error help-block-error'>{{error}}</span>
                        {% endfor %}
                        </div>  
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                        <label for="{{freight_form.target_path.label}}">{{freight_form.target_path.label}}</label>
                        {{freight_form.target_path}}
                        {% for error in freight_form.target_path.errors %}
                            <span class='help-block has-error help-block-error'>{{error}}</span>
                        {% endfor %}
                        </div>
                    </div>


                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="{{freight_form.equipment.label}}">{{freight_form.equipment.label}}</label>
                            {{freight_form.equipment}}
                            {% for error in freight_form.equipment.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{freight_form.commodity.label}}">{{freight_form.commodity.label}}</label>
                            {{freight_form.commodity}}
                            {% for error in freight_form.commodity.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="{{freight_form.commodity_amount.label}}">{{freight_form.commodity_amount.label}}</label>
                            {{freight_form.commodity_amount}}
                            {% for error in freight_form.commodity_amount.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="{{freight_form.note.label}}">{{freight_form.note.label}}</label>
                            {{freight_form.note}}
                            {% for error in freight_form.note.errors %}
                                <span class='help-block has-error help-block-error'>{{error}}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>    
            </div>
            <div class="card-footer">
                <div class="col-sm-12 text-right">                        
                    <button class="btn btn-sm btn-success" type="submit">Guardar</button>
                    <a href="{% url 'freight:freight_list' %}" class="btn btn-sm btn-white">Cancelar</a>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content%}

{% block customjs %}
    <script src="{{STATIC_URL}}plugins/touchspin/jquery.bootstrap-touchspin.min.js"></script>
{% endblock customjs %}

{% block docready %}
    {% include 'core/snippets/form_validation.html' with form=freight_form %}
    {% include 'core/snippets/messages_error.html' with form=freight_form %}
    
    $("#id_cost").TouchSpin({
        min: 0,
        max: 100000,
        step: 1000,
        buttondown_class: 'btn btn-light',
        buttonup_class: 'btn btn-light'
    });
    $("#id_commodity_amount").TouchSpin({
        min: 0,
        max: 100,
        step: 1,
        buttondown_class: 'btn btn-light',
        buttonup_class: 'btn btn-light'
    });

   $(".select2").select2({width: '100%'});
{% endblock docready %}